services:
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      # # - /etc/letsencrypt:/etc/letsencrypt

      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      # - ./nginx/sites-available:/etc/nginx/sites-available
      # - ./nginx/sites-enabled:/etc/nginx/sites-enabled
      - /etc/letsencrypt:/etc/letsencrypt
    networks:
      - rent_room_network

  api_nestjs:
    container_name: api_nestjs
    restart: always
    build:
      context: ./
    # ports:
    #   - "9000:9000"
    networks:
      - rent_room_network
    env_file:
      - ./.env
    depends_on:
      - nginx

networks:
  rent_room_network:
    driver: bridge





# services:
#   nginx:
#     image: nginx:latest
#     restart: always
#     ports:
#       - "80:80"
#       - "443:443"
#     volumes:
#       - ./nginx/conf.d:/etc/nginx/conf.d  # Ánh xạ thư mục chứa cấu hình Nginx vào container
#     networks:
#       - rent_room_network

#   api_node:
#     container_name: api_nestjs
#     restart: always
#     build:
#       context: ./
#     ports:
#       - "5000:5000"
#     networks:
#       - rent_room_network
#     env_file:
#       - ./.env
#     depends_on:
#       - nginx

# networks:
#   rent_room_network:
#     driver: bridge








# services:
#   app:
#     image: 'jc21/nginx-proxy-manager:latest'
#     restart: unless-stopped
#     ports:
#       - '80:80'
#       - '81:81'
#       - '443:443'
#     volumes:
#       - ./data:/data
#       - ./letsencrypt:/etc/letsencrypt
#     networks:
#       - rent_room_network

#   api_node:
#     container_name: api_nestjs
#     restart: always
#     build:
#       context: ./
#     ports:
#       - "5000:5000"
#     networks:
#       - rent_room_network
#     env_file:
#       - ./.env
#     depends_on:
#       - app

# networks:
#   rent_room_network:
#     driver: bridge