services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    networks:
      - rent_room_network

  api_node:
    container_name: api_nestjs
    restart: always
    build:
      context: ./
    ports:
      - "3000:3000"
    networks:
      - rent_room_network
    env_file:
      - ./.env
    depends_on:
      - app

networks:
  rent_room_network:
    driver: bridge